export const FETCH_ORDERS = 'orders/FETCH_ORDERS'
export const FETCH_ORDERS_SUCCESS = 'orders/FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'orders/FETCH_ORDERS_FAILURE'

export const CREATE_ORDERS = 'orders/CREATE_ORDERS'
export const CREATE_ORDERS_SUCCESS = 'orders/CREATE_ORDERS_SUCCESS'
export const CREATE_ORDERS_FAILURE = 'orders/CREATE_ORDERS_FAILURE'
